### ISSUE TITLE
Road map for NNPDF40MHOU

### ISSUE THREAD

**Issue by andreab1997** [NNPDF/pineko#79]
Let me collect here the steps that we are missing in order to complete NNPDF40MHOU (so that we can keep track of progresses)

- [ ] Implement `numerical FONLL`  (in charge: AB)
- [ ] Compute jets FKtables (to be investigated) 
- [ ] Include NNLO k-factors in the FKtables (to be discussed...)
- [ ] merge #75 (`pineappl` pre-release needed)
- [ ] Use the `automatic scale variations tool` to add the sv orders to the hadronic grids (in charge: AB)
- [ ] Recompute all the FKtables
- [ ] Test thcovmat and fits 
- [ ] Do the fits

Let me also tag all the people that may be involved or just interested in this (just for you to know) @cschwan @felixhekhorn @AleCandido @giacomomagni @scarlehoff

**Comment by scarlehoff** [comment]
> Include NNLO k-factors in the FKtables (to be discussed...)

This has been discussed, it just needs to be done!

**Comment by AleCandido** [comment]
> * [ ]  Implement `numerical FONLL`  (in charge: AB)

This will only marginally happen in this repo, and mainly concerns yadism and EKO.

> * [ ]  Compute jets FKtables (to be investigated)

As soon as you can, try running with a single core one jet data set, and monitor it. We are interested in peak memory consumption (you can use [`memray`](https://github.com/bloomberg/memray) or [`memory_profiler`](https://github.com/pythonprofilers/memory_profiler)) and the time required to run on single core.

**Comment by andreab1997** [comment]
> > * [ ]   Implement `numerical FONLL`  (in charge: AB)
> 
> This will only marginally happen in this repo, and mainly concerns yadism and EKO.
> 

Yes true but I wanted to have a single place in which all the steps were collected. 


> > * [ ]   Compute jets FKtables (to be investigated)
> 
> As soon as you can, try running with a single core one jet data set, and monitor it. We are interested in peak memory consumption (you can use [`memray`](https://github.com/bloomberg/memray) or [`memory_profiler`](https://github.com/pythonprofilers/memory_profiler)) and the time required to run on single core.

Yes sure, I am waiting for dom to be online again :(
